version: '3.8'
services:
  boto3.local:
    image: boto3.local
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - AWS_PROFILE
    volumes:
      - ~/.aws/:/root/.aws:ro
      - .:/app
    command:
      - python
      - main.py
