version: '3'
services:
  fastapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fastapi
    volumes:
      - "../app:/app"
    ports:
      - "8000:8000"
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    volumes:
      - "../envoy/envoy.yaml:/etc/envoy/envoy.yaml"
    ports:
      - "80:10000"
      - "9901"
